apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-microservice
  namespace: test 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-microservice
  template:
    metadata:
      labels:
        app: python-microservice
    spec:
      containers:
        - name: python-microservice
          image: ranamoghazy95/python-microservice:3.0.0
          ports:
            - containerPort: 5000  
          
