name: Terraform CI/CD

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'terraform/**'

jobs:
  terraform:
    name: Provision EKS Cluster
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan 
    
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply  -auto-approve

      # - name: Terraform Destroy
      #   working-directory: terraform
      #   run: terraform destroy -auto-approve
